Added zone module
canonical/ansible-collection pull request #8
Opened 2023-01-19 10:56 UTC by rootz1one

Ability to create/update/delete Availability Zones on MaaS

2023-02-15 06:44 UTC, rootz1one commented
@PolonaM @juremedvesek Can u please check this and other pending PRs?

2023-03-06 16:07 UTC, jurekh commented
Hi @rootz1one, MAAS team member here, thanks for your contribution! We're currently working on CI pipeline to automatically qualify pull requests and publish test reports to GitHub. When that's operational, we will be able to proceed with merging. We need the CI and the tests to be able to publish the collection in Ansible Galaxy.

2025-01-22 15:06 UTC, SK1Y101 approved these changes

2025-01-22 15:06 UTC, SK1Y101 requested changes
Looks like you need to sign the CLA, otherwise looks good

2025-09-02 07:40 UTC, skatsaounis commented
Closing this PR due to inactivity. Feel free to comment

2025-09-02 07:40 UTC, closed without merging

2025-09-02 07:40 UTC, skatsaounis commented
Closing this PR due to inactivity. Feel free to comment here in case you want to resume the work and we will quickly re-open.